name: Robot Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t bookshelf-robot .

      - name: Run Robot tests in container
        run: |
          docker run --name robot-run \
            -v ${{ github.workspace }}:/app \
            bookshelf-robot \
            robot \
              --outputdir /app/results \
              --listener allure_robotframework \
              tests

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz
          sudo mv allure-2.29.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure report
        run: |
          allure generate results -o allure-report --clean

      - name: Upload Robot results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
